
name: Windows Tests

on: [
      # pull_request, # REMOVED as windows suppoprt lacking - see https://github.com/ImperialCollegeLondon/prefect-managedfiletransfer/issues/12
      workflow_dispatch
      ]

jobs:
  run-tests:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      matrix:
        # Prefect only tests some versions on Windows - see https://github.com/PrefectHQ/prefect/blob/main/.github/workflows/windows-tests.yaml
        python-version:
          - "3.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"

      - name: Run tests
        env:
          PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./collection-tests.db"
        run: |
          uv run pytest tests -vv
